# Generated by Django 4.0 on 2022-10-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragonBall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoelaborado',
            name='imagen_id_imagen',
        ),
        migrations.AddField(
            model_name='productoelaborado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Imagen'),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
