# Generated by Django 4.0 on 2022-10-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragonBall', '0002_remove_productoelaborado_imagen_id_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(db_column='ID_Categoria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_compra',
            field=models.AutoField(db_column='ID_Compra', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='id_detallecompra',
            field=models.AutoField(db_column='ID_DetalleCompra', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='id_detalleventa',
            field=models.AutoField(db_column='ID_DetalleVenta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='id_materiaprima',
            field=models.AutoField(db_column='ID_MateriaPrima', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='id_permiso',
            field=models.AutoField(db_column='ID_Permiso', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='id_producto',
            field=models.AutoField(db_column='ID_Producto', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.AutoField(db_column='ID_Proveedor', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='id_rol',
            field=models.AutoField(db_column='ID_Rol', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='id_pago',
            field=models.AutoField(db_column='ID_Pago', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.AutoField(db_column='ID_Venta', primary_key=True, serialize=False),
        ),
    ]
