# Generated by Django 4.0 on 2022-11-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragonBall', '0002_alter_productoelaborado_precioventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoelaborado',
            name='precioventa',
            field=models.FloatField(db_column='PrecioVenta', max_length=50),
        ),
    ]
