# Generated by Django 4.0 on 2022-11-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TragonBall', '0003_alter_productoelaborado_precioventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto_id', models.ForeignKey(db_column='Producto_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='TragonBall.productoelaborado')),
                ('users_metadata', models.ForeignKey(db_column='Cliente', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='TragonBall.cliente')),
            ],
        ),
    ]
