# Generated by Django 4.0 on 2022-10-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragonBall', '0003_alter_categoria_id_categoria_alter_compra_id_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(db_column='ID_Categoria', primary_key=True, serialize=False),
        ),
    ]
