# Generated by Django 4.0.8 on 2022-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TragonBall', '0004_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='preciocompra_materiaprima',
            field=models.IntegerField(db_column='PrecioCompra_MateriaPrima'),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='stock_materiaprima',
            field=models.IntegerField(db_column='Stock_MateriaPrima'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='preciocompra',
            field=models.IntegerField(db_column='PrecioCompra'),
        ),
        migrations.AlterField(
            model_name='productoelaborado',
            name='precioventa',
            field=models.IntegerField(db_column='PrecioVenta'),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
